repos:
  # Pre-commit hooks
 - repo: https://github.com/quantco/pre-commit-mirrors-mypy
   rev: ''  # Use the sha / tag you want to point at
   hooks:
     - id: mypy-conda

 - repo: https://github.com/quantco/pre-commit-mirrors-black
   rev: ''  # Use the sha / tag you want to point at
   hooks:
     - id: black-conda

  # isort for Python import sorting
 - repo: https://github.com/quantco/pre-commit-mirrors-isort
   rev: ''  # Use the sha / tag you want to point at
   hooks:
     - id: isort-conda
